---
# tasks file for apache
- name: Instalação do apache
  apt:
    name: apache2
    state: present
  become: true

- name: Apache is running
  service:
    name: apache2
    state: started
    enable: yes
  become: true
