---
- name: Testando Variaveis
  hosts: rocky
  vars:
    message: "Mensagem de teste atraves de variavel"
    packages:
     - tree
     - vim
  tasks:
   - name: DEBUG
     ansible.builtin.debug:
       msg: "{{ message }}"

   - name: DNF | Install packges
     ansible.builtin.dnf:
       name: "{{ packages }}"
       state: latest
       update_cache: true