- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.apt:
      update_cache: true
    when: ansible_distribution == "Debian" and ansible_distribution_version == "12.8"
  
  - name: update repository rocky linux
    ansible.builtin.dnf:
      update_cache: true
    when: ansible_distribution == "Rocky" and ansible_distribution_version == "9.5"