---

- hosts: all
  become: true
  tasks:

  - name: Remove apache2 package
    ansible.builtin.apt:
      name: apache2
      state: absent
      update_cache: true
    when: "{{ ansible_distribution == 'Debian' }}"

...